### ISSUE TITLE
error

### ISSUE THREAD

**Issue by dest81** [collective/collective.jsonify#13]
Please fix:

<pre>
--- a/collective/jsonify/wrapper.py
+++ b/collective/jsonify/wrapper.py
@@ -125,7 +125,7 @@ class Wrapper(dict):
         """ Local roles of object
             :keys: _local_roles
         """
-        self['_local_roles'] = {}
+        self['_ac_local_roles'] = {}
         if getattr(self.context, '__ac_local_roles__', False):
             for key, val in self.context.__ac_local_roles__.items():
                 if key is not None:
                    self['_ac_local_roles'][key] = val
</pre>

**Comment by thet** [comment]
my pull-request is ready to be merged, IMO...

**Comment by thet** [comment]
i'm going to change that in my pull request to ``_ac_local_roles``. the blueprint in collective.jsonmigrator uses that as default key. looks like, the key in collective.jsonify was a typo. (altough, there is a xmlwalker.cfg example in plone.app.transmogrify, which uses the _local_roles key, but however...)

**Comment by thet** [comment]
@dest81 should be fixed by: https://github.com/collective/collective.jsonify/pull/12

**Comment by dest81** [comment]
Thanks!
