### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by thet** [collective/collective.jsonify#16]
@tomgross can you grant me (pypi: thet) and @djowett (pypi?) release rights on pypi? we want to make a new release of collective.jsonify.

**Comment by tomgross** [comment]
Done for @thet. @djowett is not known to pypi

**Comment by djowett** [comment]
I should be there Just logged in as "djowett" to check.

Not to worry on my part - that just leaves @thet has the responsibility :-)

On 10/04/15 15:08, Tom Gross wrote:
>
> Done for @thet <https://github.com/thet>. @djowett 
> <https://github.com/djowett> is not known to pypi
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/collective/collective.jsonify/issues/16#issuecomment-91570302>.
>

-- 
Daniel Jowett

*Jowett Enterprises Ltd*
Tel: 0333 3 553 773
Mobile: 07870 667 126
daniel@jowettenterprises.com
www.jowettenterprises.com

**Comment by thet** [comment]
released 1.0
