### ISSUE TITLE
Features from tt-slandchildren branch?

### ISSUE THREAD

**Issue by thet** [collective/collective.jsonify#17]
This branch seems to have some nice additions: https://github.com/collective/collective.jsonify/compare/tt-slandchildren

@jone do you think your contributions would be valueable for merging/cherry picking into the master branch? the master branch has changed a lot, so this must be done carefully.
@jone what are you using for importing in plone?

**Comment by jone** [comment]
@thet yes, I think some things are useable and should be applied to master, but there are also some custom imports (e.g. https://github.com/collective/collective.jsonify/blob/tt-slandchildren/collective/jsonify/wrapper.py#L11) which will break when the addons are missing..

**Comment by thet** [comment]
Stale issue.
