### ISSUE TITLE
"export your site’s content to json files for multiple re-use" How?

### ISSUE THREAD

**Issue by djowett** [collective/collective.jsonify#20]
@thet do you mind adding a hint / link on how to use json files?

**Comment by idgserpro** [comment]
@djowett You can try to do the following, at least for archetypes (dexterity may be similar but I haven't tested it):

- Add collective.jsonify to your installation;
- Create your content normally through the web interface in a Vanilla Plone Site;
- Use the External Method "export_content" from jsonify (check it's documentation to know how to add them) to export what you want to json;
- Put all these jsons inside a folder in your package;
- Create a transmogrifier similar to this one [presented in an issue in collective.jsonmigrator](https://github.com/collective/collective.jsonmigrator/issues/13) (this is just a simple example, other blueprints may be needed for your situation). Remember to call the transmogrifier in setuphandlers (or other place in your code) like it's said in the issue, and to add collective.jsonmigrator as a dependency in the package you want to import the jsons.

...but to work flawlessly this way, we need a new release of collective.jsonmigrator. Can you help us [there somehow](https://github.com/collective/collective.jsonmigrator/issues/13)?

**Comment by thet** [comment]
I've created a repo, which much of my transmogrifier experience. That worked for a recent migration project
I had the code within another package and externalized just now, so don't expect that to work in the current state.
A little HowTo use is in the readme.

https://github.com/thet/programmatic.transmogrifier

hope that helps

**Comment by thet** [comment]
New releases:
- collective.jsonify
- mr.migrator

Needs new releases:
- plone.app.transmogrifier @agitator
- collective.transmogrifier @lentinj 
- collective.jsonmigrator @ericoandrei

**Comment by lentinj** [comment]
Done.

**Comment by ericof** [comment]
Done
